---
title: "GroupModule"
author: "cjlw2020"
date: "11/22/2019"
output:
  pdf_document: default
  html_document: default
---

```{r}
#section here introducing what lidar is & how to download the data
#info & data download here:
#https://sites.google.com/bu.edu/ge505/lab-4-lidar?authuser=0
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Import LIDAR data
##Download packages "lidR" and "raster"
```{r}
#install.packages("lidR")
library(lidR) #this one for sure
library(sf)
library(ggplot2)
#library(raster)
#ibrary(rgeos)
#library(mapview)
```

##Get raw LIDAR data into R
```{r}
#setwd("C:/Users/clint/Desktop/Stuff")
#las <- readLAS("USGS_LPC_MA_Sndy_CMPG_2013_19TCG255905_LAS_2015.las")
#nk: 
las <- readLAS("~/Downloads/Lab4_Data/USGS_LPC_MA_Sndy_CMPG_2013_19TCG255905_LAS_2015/USGS_LPC_MA_Sndy_CMPG_2013_19TCG255905_LAS_2015.las")
plot(las) #first look
```

#Transition LIDAR data to DEM
```{r}
#let's explain what dem is 
dem <-  grid_terrain(las, algorithm = tin())
plot(dem)
```
#Convert to DSM + create hillshade model
```{r}
proj4string(las) <-CRS("+proj=utm +zone=19 +datum=NAD83") #assigning coord ref system
dsm1 <- grid_canopy(las, res = 1, dsmtin())
col <- height.colors(100) #how many colors to use, the more colors the better resolution in the plot
plot(dsm1, col = col)
slope  <- terrain(dsm1, opt='slope')
aspect <- terrain(dsm1, opt='aspect')
hill <- hillShade(slope, aspect, 45, 120)
plot(hill, col=grey(0:100/100), legend=FALSE, main='Boston University')
plot(dsm1, col=rainbow(25, alpha=0.35),add=TRUE)
```

#Nice building shp file plot
```{r eval = FALSE}
BU_buildings_shp <- st_read("~/Downloads/Lab4_Data/Building_structures_bu/building_structures_bu.shp")
BU_buildings <- ggplot() + 
  geom_sf(data = BU_buildings_shp, size = 0.5, color = "black", fill = "cyan1") + 
  ggtitle("BU Buildings") + 
  coord_sf()
plot(BU_buildings)
```

#Plot Building Vector File on Raster
```{r eval = FALSE}
dsm2 <- projectRaster(dsm1, crs = crs(BU_buildings_shp[2]))
dsm3 <- crop(dsm2, BU_buildings_shp[2]) #there are 16 different options instead of "2" here, not sure which one we want

hill2 <- projectRaster(hill, crs = crs(BU_buildings_shp[2]))
hill3 <- crop(hill2, BU_buildings_shp[2]) #there are 16 different options instead of "2" here, not sure which one we want

#aligned plot, still has extra region in the buildings that part we don't need:
plot(hill3, col=grey(0:100/100), legend=FALSE, main ='Boston University')
plot(BU_buildings_shp[2],add=TRUE)
plot(dsm3,col=rainbow(25, alpha=0.35),add=TRUE)
```




#Outdated script
#Get a processed DSM file into R
```{r eval=FALSE}
dsm <- raster("bu_dsm.tif")
plot(dsm)
```
#Create a hillshade from DSM
```{r eval=FALSE}
slope  <- terrain(dsm, opt='slope')
aspect <- terrain(dsm, opt='aspect')
hill <- hillShade(slope, aspect, 45, 120)
quartz()
plot(hill, col=grey(0:100/100), legend=FALSE, main='Boston University')
plot(dsm1, col=rainbow(25, alpha=0.35), add=TRUE)
```
#unaligned raster + vector file
```{r}
plot(hill, col=grey(0:100/100), legend=FALSE, main ='Boston University')
plot(BU_buildings,
     add = TRUE)
plot(dsm1, col=rainbow(25, alpha=0.35), add=TRUE)
```



